% Verbos regulares en infinitivo terminados en -ar
verbo(ar, 'amar').
verbo(ar, 'bailar').
verbo(ar, 'cantar').
verbo(ar, 'caminar').
verbo(ar, 'cocinar').
verbo(ar, 'comprar').
verbo(ar, 'descansar').
verbo(ar, 'dibujar').
verbo(ar, 'escuchar').
verbo(ar, 'estudiar').
verbo(ar, 'hablar').
verbo(ar, 'jugar').
verbo(ar, 'limpiar').
verbo(ar, 'mirar').
verbo(ar, 'nadar').
verbo(ar, 'pasear').
verbo(ar, 'pintar').
verbo(ar, 'saltar').
verbo(ar, 'tomar').
verbo(ar, 'trabajar').
verbo(ar, 'viajar').
verbo(ar, 'visitar').
verbo(ar, 'volar').
verbo(ar, 'votar').
verbo(ar, 'ayudar').
verbo(ar, 'buscar').
verbo(ar, 'cambiar').
verbo(ar, 'compartir').
verbo(ar, 'contestar').
verbo(ar, 'entrar').
verbo(ar, 'escalar').
verbo(ar, 'ganar').
verbo(ar, 'gastar').
verbo(ar, 'llegar').
verbo(ar, 'pagar').
verbo(ar, 'regresar').
verbo(ar, 'saludar').
verbo(ar, 'terminar').
verbo(ar, 'tratar').
verbo(ar, 'alabar').
verbo(ar, 'apagar').
verbo(ar, 'cantar').
verbo(ar, 'celebrar').
verbo(ar, 'copiar').
verbo(ar, 'cultivar').
verbo(ar, 'desear').
verbo(ar, 'educar').
verbo(ar, 'enviar').
verbo(ar, 'fumar').
verbo(ar, 'llamar').
verbo(ar, 'necesitar').
verbo(ar, 'olvidar').
verbo(ar, 'preparar').
verbo(ar, 'recibir').
verbo(ar, 'rezar').
verbo(ar, 'soñar').
verbo(ar, 'tocar').
verbo(ar, 'usar').

% Verbos regulares en infinitivo terminados en -er
verbo(er, 'aprender').
verbo(er, 'beber').
verbo(er, 'comer').
verbo(er, 'correr').
verbo(er, 'creer').
verbo(er, 'deber').
verbo(er, 'leer').
verbo(er, 'meter').
verbo(er, 'poseer').
verbo(er, 'prometer').
verbo(er, 'romper').
verbo(er, 'tejer').
verbo(er, 'vender').
verbo(er, 'abarcar').
verbo(er, 'absorber').
verbo(er, 'admitir').
verbo(er, 'barrer').
verbo(er, 'convencer').
verbo(er, 'defender').
verbo(er, 'depender').
verbo(er, 'encender').
verbo(er, 'entender').
verbo(er, 'esconder').
verbo(er, 'extender').
verbo(er, 'morder').
verbo(er, 'ofrecer').
verbo(er, 'perder').
verbo(er, 'prender').
verbo(er, 'responder').
verbo(er, 'sorprender').
verbo(er, 'tejer').
verbo(er, 'temer').
verbo(er, 'toser').
verbo(er, 'valer').
verbo(er, 'volver').

% Verbos regulares en infinitivo terminados en -ir
verbo(ir, 'abrir').
verbo(ir, 'admitir').
verbo(ir, 'asistir').
verbo(ir, 'cubrir').
verbo(ir, 'decidir').
verbo(ir, 'describir').
verbo(ir, 'descubrir').
verbo(ir, 'discutir').
verbo(ir, 'escribir').
verbo(ir, 'existir').
verbo(ir, 'insistir').
verbo(ir, 'ocurrir').
verbo(ir, 'partir').
verbo(ir, 'permitir').
verbo(ir, 'prohibir').
verbo(ir, 'recibir').
verbo(ir, 'repetir').
verbo(ir, 'subir').
verbo(ir, 'sufrir').
verbo(ir, 'vivir').
verbo(ir, 'cumplir').
verbo(ir, 'dividir').
verbo(ir, 'interrumpir').
verbo(ir, 'percibir').
verbo(ir, 'consumir').
verbo(ir, 'construir').
verbo(ir, 'instruir').
verbo(ir, 'inscribir').
verbo(ir, 'omitir').
verbo(ir, 'permitir').
verbo(ir, 'referir').
verbo(ir, 'remitir').
verbo(ir, 'transmitir').


